name: Pin Browsers
description: Install and setup Chrome and Firefox

# List of browser versions
# Chrome (ubuntu): https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable
# Chrome versions: https://versionhistory.googleapis.com/v1/chrome/platforms/linux/channels/stable/versions

inputs:
  chrome-version:
    description: Chrome version to install
    default: "latest"
  token:
    description: github PAT
    required: true

runs:
  using: composite
  steps:
    - name: Setup latest Chrome
      if: ${{ inputs.chrome-version == 'latest' }}
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: ${{ inputs.chrome-version }}
    - name: Print latest Chrome version
      if: ${{ inputs.chrome-version == 'latest' }}
      shell: bash
      run: google-chrome-stable --version
    - name: Setup Chrome with specific version
      if: ${{ inputs.chrome-version != 'latest' }}
      shell: bash
      env:
        CHROME_VERSION: ${{ inputs.chrome-version }}
        GH_TOKEN: ${{ inputs.token }}
      run: |
        if [ -n "$CHROME_VERSION" ]; then
          sudo apt-get update
          sudo apt-get -y install libu2f-udev
          
          curl -sS https://webi.sh/gh | sh
          source ~/.config/envman/PATH.env
          
          mkdir google-chrome-setup 
          gh release download 1.0.0 --repo DevExpress/tmp-chrome-image --pattern "*.deb" --dir ./google-chrome-setup  
          sudo dpkg -i google-chrome-setup/google-chrome-stable_121.0.6167.184-1_amd64.deb
          google-chrome-stable --version
        
          rm -rf google-chrome-setup  
        else
          echo "Skip Chrome upgrade"
        fi
